version: "3"

services: 
    db:
        image: postgres:12.1-alpine
        container_name: db
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_PASSWORD: "nyaruka"
            POSTGRES_USER: "casepro"
            POSTGRES_DB: "casepro"
        # volumes:
        #   - postgres_data:/var/lib/postgresql/data
    # redis:
    #     image: redis
    #     container_name: redis
    #     # ports:
    #         # - "6379:6379"
    #     volumes:
    #       - redis_data:/data
    casepro:

        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: casepro
        links:
            - db 
        depends_on: 
            - db
            # - redis
        ports:
            - "8000:8000"

# volumes:
#     postgres_data:
#     redis_data: 