version: "3"

services: 
    db:
        image: postgres:alpine
        ports:
            - "5431:5432"
        environment: 
            POSTGRES_PASSWORD: "nyaruka"
            POSTGRES_USER: "casepro"
            POSTGRES_DB: "casepro"
    app:
        build:
            context: .
            dockerfile: dev.Dockerfile
        links:
            - db
        depends_on: 
            - db
        ports:
            - "8000:8000"